README.md, config/config_testdata/config_manual_load.json, config/config_testdata/config_manual_load_override.json, config/json.go, config/json_test.go, config_examples/config.json, core/engine.go, core/engine_test.go, core/types/hammer.go, core/types/hammer_test.go
=> manual_load config json to hammer creation imp

README.md, config/config_testdata/config.json, config/json.go, config/json_test.go, config_examples/config.json, core/scenario/service.go, core/scenario/service_test.go, core/types/hammer_test.go, core/types/scenario.go
=> Sleep between steps logic implemented

config/config_testdata/config.json, config/json.go, config/json_test.go, core/report/stdout.go, core/scenario/requester/http.go, core/types/response.go, core/types/scenario.go
Name support for scenario steps.
=> Ddosify 121 name property in step

core/types/hammer_test.go, core/types/scenario.go
=> step id uniqueness check

core/engine.go, core/proxy/base.go, core/proxy/single.go, core/scenario/requester/http.go
=> add second tls time fetch logic

core/engine.go, core/types/scenario.go
- The letter d is missing
- len to arrLen
=>  The letter d is missing

README.md
Hi!
I'm maintainer of  ddosfiy on FreeBSD. 
https://www.freshports.org/benchmarks/ddosify/
Can you add instructions for installing ddosfiy on FreeBSD?
=> Adding instructions to install on FreeBSD

.devcontainer/Dockerfile.dev, go.mod, go.sum
Bump the `x/net` version to 0.8.0 for security purposes. 
=> Bump x/net for security

README.md, core/scenario/scripting/assertion/assert_test.go, core/scenario/scripting/assertion/evaluator/evaluator.go, core/scenario/scripting/assertion/evaluator/function.go
=> add greater than func

core/scenario/scripting/assertion/assert_test.go, core/scenario/scripting/assertion/evaluator/evaluator.go, core/scenario/scripting/assertion/evaluator/function.go
Range function now can take floats as arguments and can compare integer and float extracted values against int or float limits.
=> refactor range func 

core/scenario/requester/http.go
=> copy req body on only debug mode

core/scenario/requester/http.go
=> copy req array

core/scenario/requester/http.go
=> req body store limit

core/engine.go, core/scenario/requester/http.go, core/scenario/scripting/injection/environment.go, core/scenario/scripting/injection/environment_dynamic.go, core/scenario/scripting/injection/environment_test.go
- [ x] Bug fix (non-breaking change which fixes an issue)
=> fix injection error bug

core/scenario/requester/http.go
=> update client timeout on user modes

core/scenario/requester/http.go
=> classify 'Client.Timeout exceeded while awaiting headers' as connTimeout

core/assertion/service.go, core/report/aggregator.go, core/report/stdout.go, core/report/stdoutJson.go, core/report/stdoutJson_test.go
=> show failed criterias on debug mode

config/json.go, main_benchmark_test.go
=> check status code for remote file on multipart

core/scenario/scripting/assertion/assert_test.go, core/scenario/scripting/assertion/evaluator/evaluator.go, core/scenario/scripting/assertion/evaluator/function.go, engine_docs/README.md
=> add p98 func

assets/ddosify.profile, scripts/install.sh
https://github.com/ddosify/ddosify/issues/215
=> Fix install script

core/report/stdout.go
unnecessary use of fmt.Sprintf
=> chore: unnecessary use of fmt.Sprintf

core/engine_test.go, core/scenario/scripting/injection/init.go, core/types/response.go, core/types/scenario.go
=> Fix some typos in comments

core/scenario/client_pool.go
=> chore: fix function name

.github/workflows/docs.yml, .lycheeignore, README.md, ddosify_engine/README.md
Adds <https://lychee.cli.rs/> as a link checker to the CI
=> Add link checker for the documentation
